# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
os:
  - linux
  - osx
r:
  - oldrel
  - release
  - devel
pandoc_version: 1.16
sudo: false
cache: packages
after_success:
  - Rscript -e 'covr::codecov()'
  